### ISSUE TITLE
CSS가  user정답 화면이 상황에 따라 다르게 반영되는 문제

### ISSUE THREAD

**Issue by towozy** [Front-line-dev/markup-educator#76]
아래와 같은 오류를 발견하여 제보 드립니다.
- 재현방법: 새로고침 후, css 소스에서 `}`를 지웠다 다시 써도 처음 반영된 화면만 유지됨.

![image](https://github.com/Front-line-dev/markup-educator/assets/2697040/fd205d64-6c16-435e-878c-9dff08cbc96c)

![image](https://github.com/Front-line-dev/markup-educator/assets/2697040/de019bfd-afbb-4718-8be5-edf7767473f7)

#### 이슈 재현 샘플 코드
```css
.container {
  padding-bottom: 20px;
  text-align: center;
  background-color: white;
}
.button {
  width: 70px;
  height: 70px;
  margin-top: 20px;
  &:first-child {
    border: 3px green solid;
  }
  &:nth-child(2) {
    border: 3px green dashed;
  }
  &:nth-child(3) {
    border: 3px green dotted;
  }
  &:nth-child(4) {}
    
  }
  &:nth-child(5) {
    border: 3px green;
    /* 50% */
  }
}
```
